[Components] Add sistent naming convention for our components
layer5io/sistent pull request #465
Opened 2024-01-17 21:46 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

For being consistent we can use the sistent naming convention instead of mui for exporting these  theme based components.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

2024-01-25 05:37 UTC, sudhanshutech commented
> So we're only just naming the custom components, not the exported components to be used in Meshery?

They might because i think these styled component will only play major role when wrapped with sistent provider right!.
The naming is for only to keep our sistent codebase looks like its our own components and colors.

2024-01-28 09:22 UTC, aabidsofi19 requested changes

2024-01-28 09:22 UTC, aabidsofi19 commented on packages/components/src/theme/components/checkbox.modifier.ts
> +export const SistentCheckbox: Components<Theme>['MuiCheckbox'] = {
@sudhanshutech  using sistent as prefix is redundant ( as they will be scoped under sistent ) , I would suggest use `Base-<Component>` for unstyled / customizable component and `<Functionality-<Component>` for customized and ready to use ones  , @nebula-aac  whats your opinion ?

2024-01-28 09:23 UTC, aabidsofi19 commented
@sudhanshutech  @nebula-aac  I would suggest using our custom convention for both private and public components

2024-02-03 12:25 UTC, aabidsofi19 commented on packages/components/src/theme/components/checkbox.modifier.ts
> +export const SistentCheckbox: Components<Theme>['MuiCheckbox'] = {
@nebula-aac  @sudhanshutech    we dont need to have a complex naming convention , lets agree of something simple and stay consistent

2024-04-15 01:08 UTC, closed without merging