Fix feedback component to use standard style
layer5io/sistent pull request #643
Opened 2024-06-06 13:40 UTC by sudhanshutech

**Notes for Reviewers**

This PR fixes #

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [ ] Yes, I signed my commits.

2024-06-06 15:23 UTC, leecalcote reviewed
Is the white text in the button standard for disabled components? No, right?

2024-06-07 00:33 UTC, captain-Akshay requested changes
Since you are there @sudhanshutech the success screen in dark mode need a white text.

2024-06-07 20:55 UTC, leecalcote commented
merge conflict

2024-06-10 12:50 UTC, captain-Akshay approved these changes

2024-06-10 12:56 UTC, merged