test(playwright): adding data-testid to support e2e tests
layer5io/sistent pull request #744
Opened 2024-10-02 06:58 UTC by yash37158

**Notes for Reviewers**
Added data-testid for supporting playwright e2e test for UI/Environments
This PR fixes [UI/environment Playwright test](https://github.com/meshery/meshery/pull/12088)

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

2024-10-10 12:07 UTC, jerensl requested changes

2024-10-10 12:07 UTC, jerensl commented on src/custom/TransferModal/TransferList/TransferList.tsx
> -      <List dense component="div" role="list">
I think it's better to use test id in meshery/meshery as the parent of this sistent element, and find them by role or aria-label. It's enough to distinguish the element i think. Wdyt?

https://playwright.dev/docs/api/class-framelocator#frame-locator-get-by-label

2024-10-31 13:07 UTC, jerensl commented
> @yash37158 Are you suggesting to add `data-testid` to support `e2e` in `sistent` or from Meshery UI?
> 
> If it is meant for Meshery UI, I would suggest against this, as it can confuse future `e2e` testing for `sistent` versus Meshery UI.

I agree with this especially MUI styled do not accept non standard attributes like data-testid if im not mistaken

2024-11-06 22:23 UTC, yash37158 commented
@jerensl I understand that the Meshery UI has some reliability issues when it comes to consistently loading components. Additionally, dependency injection isn't feasible within the Playwright tests. What other options are available?

2024-11-14 19:56 UTC, closed without merging