feat: Added Panel component to sistent
layer5io/sistent pull request #863
Opened 2024-12-27 05:52 UTC by Vidit-Kushwaha

**Notes for Reviewers**

This PR introduces a `Panel` component to the Sistent library to ensure consistency across Layer5 projects. The Panel component provides a customizable and reusable UI element for layout management. 

Additionally, the following packages have been added to support the component's features:
- `"re-resizable": "^6.10.3"`: For implementing resizable panel functionality.
- `"react-draggable": "^4.4.6"`: To enable drag-and-drop capabilities.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**

- [x] Yes, I signed my commits.

2024-12-30 10:54 UTC, SAHU-01 commented
@Vidit-Kushwaha, thank you for woking on this could you add it as a website agenda item in the meeting minutes?

2024-12-30 10:57 UTC, amitamrutiya requested changes
Don't use inline css for all the components create styled components for that.

2025-01-02 08:43 UTC, amitamrutiya commented
Are we done with all of the changes and all the necessary props?. Before merge this PR replace all the panels inside the extension use it from the sistent. Create a PR for that then we'll merge this.

2025-01-13 17:55 UTC, amitamrutiya approved these changes

2025-01-17 08:30 UTC, amitamrutiya commented
Lint is failing fix this

2025-01-20 04:35 UTC, amitamrutiya commented
I am not going to merge this PR until you create PR in extension repo that uses this sistent panel component @Vidit-Kushwaha .

2025-01-23 04:09 UTC, amitamrutiya commented
Is it done?

2025-01-24 15:21 UTC, Vidit-Kushwaha commented
Yes It is done I have created a separate PR for this in meshery-extensions

2025-01-27 14:51 UTC, merged