Setup SVG icon library
layer5io/sistent pull request #9
Opened 2023-08-21 22:38 UTC by nebula-aac

**Notes for Reviewers**

This PR creates an SVG icon library that consists of most common icons we've been using across multiple repos.

**[Signed commits](../blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [ ] Yes, I signed my commits.

2023-08-22 04:20 UTC, aabidsofi19 requested changes

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/types.ts
> +}
The Icon Types should inherit from svg ( Our  should be actually just wrappers over svgs )  

```suggestion
import { SVGAttributes } from 'react';
export interface IconProps extends SVGAttributes<SVGElement> {
    children?: never;
    color?: string;
    title?: string;
}
```

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/ZoomOutIcon.tsx
> +export const ZoomOutIcon: FC<IconProps> = ({
we are still having inconsistency about which properties are supported by different icons .

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/ApplicationIcon.tsx
> +const ApplicationIcon: FC<IconProps> = ({
we should separate solid, outline and  color icons so we dont  have  some icons doing  one thing and others different

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/CloudSavedIcon.tsx
> +    ...props
some icons are supporting additional props but others dont ,  i think every icon should support all the svg attributes .

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/CloudSavingIcon.tsx
> +                fill="#5f6368"
hardocoded fill ..

2023-08-22 04:20 UTC, aabidsofi19 commented on packages/svg/src/icons/ComponentIcon.tsx
> +export const ComponentIcon: FC<IconProps> = ({
conditionals cause inconsistency

2023-08-22 07:41 UTC, aabidsofi19 commented
@nebula-aac  are we going to publish icons , components etc separately ...

2023-08-22 17:16 UTC, aabidsofi19 commented
@nebula-aac  i think  we should be fowarding ref to svg , this can be a  beginner issue after  this ..

2023-08-22 17:21 UTC, aabidsofi19 commented on package.json
> +    "workspaces": ["./apps/*", "./packages/*"]
i prev had issue with "./packages/*" and had to change to "packages/*"  .

2023-08-22 17:21 UTC, aabidsofi19 commented on packages/svg/src/icons/CloudSavingIcon.tsx
> +                {...props}
we are passing same props to root svg and path  .

2023-08-22 17:22 UTC, aabidsofi19 commented
Looks great  :)

2023-08-22 18:17 UTC, nebula-aac commented
I'm already working on separating the icons so it can either filled or outlined on a separate PR.

2023-08-23 04:26 UTC, merged

2023-08-23 04:28 UTC, aabidsofi19 commented
@nebula-aac  can you pls create a small readme of how to create a new icon like ( what should be default values and general guidelines  ) .  or maybe a reviewing guide to say